title: 3i Space Dynamics
logo: /assets/img/logo_3isd.png
description: This laboratory is devoted to space mission design research with an empahsis on discovering synergies across disciplines that may fundamentally improve systems or design processes for space exploration. 
show_downloads: true
google_analytics: false
theme: jekyll-theme-minimal
