title: Interactive Immersive Intelligent Space Dynamics
logo: /assets/img/logo_3isd.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
